using Microsoft.JSInterop;

namespace Turnwise.Web.Services;

/// <summary>Triggers a browser file download from server-generated bytes (Blazor Server has no filesystem to save to directly).</summary>
public sealed class FileDownloadService(IJSRuntime js)
{
    public async Task DownloadAsync(string fileName, string contentType, byte[] content)
    {
        await using var module = await js.InvokeAsync<IJSObjectReference>("import", "./js/fileDownload.js");
        await module.InvokeVoidAsync("downloadFileFromBase64", fileName, contentType, Convert.ToBase64String(content));
    }
}
